apiVersion: v1
kind: Pod
metadata:
  name: hello-pod-with-1-container
  labels : 
    app : web
spec:
  containers:
    - name: web-ctr
      image : us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
      ports:
        - containerPort: 8080