apiVersion: v1
kind: Pod
metadata:
  name: pod-con-2-contenedores 
spec:
  containers:
    - name: container1
      image : nginx:latest
      ports:
      - containerPort: 80
    - name: my-app
      image: tomcat:latest
      ports:
      - containerPort: 8080