apiVersion: v1
kind: Pod
metadata:
  name: hello-pod 
spec:
  containers:
    - name: web-ctr
      image : gcr.io/google-samples/hello-app:1.0
      ports:
        - containerPort: 8080
    - name: helper-ctr
      image : gcr.io/google-samples/hello-app:1.0
      ports:
      - containerPort: 80