apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-app-deployment
  labels:
    app: httpd-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-app
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      containers:
      - name: httpd-app
        image: httpd
        ports:
        - containerPort: 80
