apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-app-deployment
  labels:
    app: wordpress-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
      - name: wordpress-app
        image: wordpress:latest
        #image: httpd
        ports:
        - containerPort: 80
