apiVersion: v1
kind: Pod
metadata:
  name: hello-pod 
spec:
  containers:
    - name: web-ctr
      image : nginx
      ports:
        - containerPort: 8080
    - name: helper-ctr
      image : nginx:latest
      ports:
      - containerPort: 9113