apiVersion: v1
kind: Service
metadata:
  name: ps-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort : 31111
    targetPort: 8080            
    protocol : TCP
  selector:
    app : web