apiVersion: v1
kind: Service
metadata:
  name: nfs-web-loadbalancer-service
spec:
  selector:
    #app: nfs-web
    app: local-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer