apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-monitoring-prometheus
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 192.168.122.20
    path: "/mnt/nfs_share/monitoring-data/prometheus"