apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-monitoring-prometheus
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 100Mi 