apiVersion: v1                                                                                
kind: PersistentVolume                                                                        
metadata:                                                                                     
  name: pv-mysql                                                                              
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  nfs:
    server: 192.168.122.20
    path: "/mnt/nfs_share/databases/mysql" 
