apiVersion: v1
kind: Service
metadata:
  name: wordpress-clusterip-service
spec:
  selector:
    app: wordpress-app
  ports:
  - name: http
    port: 80
    targetPort: 80
#  type: ClusterIP
#  clusterIP: None
