apiVersion: v1
kind: Service
metadata:
  name: wordpress-nodeport-service
spec:
  selector:
    app: wordpress-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
