#Requisito tener un servicio loadbalancer que otorgue la ip para ser expuesto
apiVersion: v1
kind: Service
metadata:
  name: wordpress-app-service
spec:
  selector:
    app: wordpress-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer