#Requisito tener un servicio loadbalancer que otorgue la ip para ser expuesto
apiVersion: v1
kind: Service
metadata:
  name: hello-loadbalancer-service
spec:
  selector:
    app: hello
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer