apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hello-congresofoss
spec:
  ingressClassName: nginx
  rules:
  - host: hello.congresofoss.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-v1-svc
            port: 
              number: 80

